version: '3'
services:
  www:
    image: php:apache      
    container_name: php
    build:
      context: .                    
      dockerfile: Dockerfile      
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html/        
    links:
      - db
    networks:
      - default
  db:
    image: mysql:latest 
    container_name: db 
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: test_feladat
      MYSQL_USER: test_feladat
      MYSQL_ROOT_PASSWORD: mPPUsybBQnRVRdJQ
      MYSQL_PASSWORD: mPPUsybBQnRVRdJQ
       
    
    volumes:
      - my-db:/var/lib/mysql
    ports:
      - '3306:3306'
  
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    ports:
     - "8081:80"
    environment:
      MYSQL_ROOT_PASSWORD: mPPUsybBQnRVRdJQ
      PMA_HOST: db   
      PMA_USER: test_feladat
      PMA_PASSWORD: mPPUsybBQnRVRdJQ

volumes: 
  my-db:
